{
  "DurabilityWoodenHammer": 302,
  "DurabilityStoneHammer": 650,
  "DurabilityIronHammer": 1300,
  "DurabilityGoldHammer": 750,
  "DurabilityLapisHammer": 1100,
  "DurabilityRedstoneHammer": 1100,
  "DurabilityObsidianHammer": 11200,
  "DurabilityDiamondHammer": 8025,
  "DurabilityEmeraldHammer": 9768,
  "DurabilityNetheriteHammer": 13675
}